const map = require("./src/graphql.server.json")
const { promises: fsp } = require("fs")

/**
 * Automatically generate persistent queries from
 * the `graphql.server.json` file generated by `graphql-codegen`
 * when executing the `npm run codegen` script.
 *
 * This function is configured in `codegen.yml`
 * to be automatically executed after `graphql-codegen` is done.
 */
async function main() {
    await Promise.all(
        Object.entries(map).map(([hash, query]) =>
            fsp.writeFile(
                `${__dirname}/.persisted_operations/${hash}.graphql`,
                query
            )
        )
    )
}

main().catch((e) => {
    console.error(e)
    process.exit(1)
})
