version: "3"

services:
    everglot-app:
        environment:
            NODE_ENV: "development"
            ROARR_LOG: "true"
    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
