version: "3"

services:
    everglot-app:
        image: everglot/everglot-app:latest
        build:
            context: .
        restart: always
        working_dir: /home/node/app
        depends_on:
            - everglot-db
        environment:
            PGUSER: ${POSTGRES_USER:?Please set POSTGRES_USER}
            PGPASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
            PGDATABASE: ${POSTGRES_DB:?Please set POSTGRES_DB}
            PGHOST: ${PGHOST:-everglot-db}
            PGPORT: ${PGPORT:-5432}
            DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PGHOST:-everglot-db}:${PGPORT}/${POSTGRES_DB}"
            SESSION_COOKIE_VALIDATION_SECRETS: ${SESSION_COOKIE_VALIDATION_SECRETS:?Please set SESSION_COOKIE_VALIDATION_SECRETS}
            AGORA_APP_CERTIFICATE: ${AGORA_APP_CERTIFICATE:?Please set AGORA_APP_CERTIFICATE}
            SENDINBLUE_API_KEY: ${SENDINBLUE_API_KEY:?Please set SENDINBLUE_API_KEY}
            REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY:?Please set REFRESH_TOKEN_SECRET_KEY}
            REFRESH_TOKEN_JWKS: ${REFRESH_TOKEN_JWKS:?Please set REFRESH_TOKEN_JWKS}
            DEMO_TOKEN: ${DEMO_TOKEN}
            DEMO_USER_EMAIL: ${DEMO_USER_EMAIL}
            DEMO2_TOKEN: ${DEMO2_TOKEN}
            DEMO2_USER_EMAIL: ${DEMO2_USER_EMAIL}

    everglot-db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER:?Please set POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB:?Please set POSTGRES_DB}
