version: "3"

services:
    everglot-app:
        image: everglot/everglot-app:latest
        build:
            context: .
        restart: always
        working_dir: /home/node/app
        environment:
            PGUSER: ${POSTGRES_USER:?Please set POSTGRES_USER}
            PGPASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
            PGDATABASE: ${POSTGRES_DB:?Please set POSTGRES_DB}
            PGHOST: ${PGHOST:-db}
            PGPORT: ${PGPORT:-5432}
            DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PGHOST:-db}:${PGPORT}/${POSTGRES_DB}"
            SESSION_COOKIE_VALIDATION_SECRETS: ${SESSION_COOKIE_VALIDATION_SECRETS:?Please set SESSION_COOKIE_VALIDATION_SECRETS}

networks:
    default:
        external:
            name: everglot-network
