version: "3"

services:
    everglot-app:
        volumes:
            - ./:/home/node/app
        environment:
            NODE_ENV: "development"
            ROARR_LOG: "true"
            HOST: "0.0.0.0"
            PORT: "3000"
        entrypoint: entrypoints/test.sh
        command: '/bin/sh -c "npm run start | npx @roarr/cli pretty-print"'
        ports:
            - "127.0.0.1:3000:3000"

    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
