version: "3"

services:
    everglot-app:
        volumes:
            - ./:/home/node/app
        ports:
            - "0.0.0.0:8002:3000"
            - "0.0.0.0:10000:10000"
        environment:
            NODE_ENV: "test"
            NODE_OPTIONS: "--max_old_space_size=8192"
            ROARR_LOG: "true"
            PGUSER: "everglot_app_user"
            PGPASSWORD: "everglot_app_pass"
            PGDATABASE: "everglot_app_db"
            PGHOST: "everglot-db"
            PGPORT: "5432"
            DATABASE_URL: "postgres://everglot_app_user:everglot_app_pass@$everglot-db:5432/everglot_app_db"
            HOST: "0.0.0.0"
            PORT: "3000"
        entrypoint: entrypoints/dev.sh
        # We only show log messages from level DEBUG upwards to de-clutter the output.
        command:
            [
                "/bin/sh",
                "-c",
                'npm run dev | roarr pretty-print --fe ''{"context.logLevel":{gt:10}}''',
            ]
        # Run the service with the following command to show log messages with level TRACE as well.
        # You can usually pass it at the end of your `docker-compose` shell command.
        # command: ["/bin/sh", "-c", "npm run dev | roarr pretty-print"]

    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
        ports:
            - "127.0.0.1:5432:5432"
