version: "3"

services:
    everglot-app:
        volumes:
            - ./:/home/node/app
        environment:
            NODE_ENV: "development"
            ROARR_LOG: "true"
        entrypoint: entrypoints/test.sh
        command: "node __sapper__/build"
        ports:
            - "127.0.0.1:3000:3000"

    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
