version: "3"

services:
    everglot-app:
        entrypoint: "npm run test -- --forceExit"
        volumes:
            - ./:/home/node/app
        environment:
            NODE_ENV: "development"
    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
