version: "3"

services:
    everglot-app:
        environment:
            NODE_ENV: "development"
            ROARR_LOG: "true"
            HOST: "0.0.0.0"
            PORT: "3000"
        # Run app as if it were in production.
        entrypoint: entrypoints/prod.sh

    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
