version: "3"

services:
    everglot-app:
        entrypoint: "npm run dev"
        volumes:
            - ./:/home/node/app
        ports:
            - "127.0.0.1:8002:3000"
            - "127.0.0.1:10000:10000"
