version: "3"

services:
    everglot-app:
        volumes:
            - ./:/home/node/app
        environment:
            NODE_ENV: "development"
            ROARR_LOG: "true"
            HOST: "0.0.0.0"
            PORT: "3000"
        entrypoint: entrypoints/test-after-db.sh
        command: ["/bin/sh", "-c", "npm run dev | roarr pretty-print"]
        # Avoid building the same image twice.
        image: everglot-app-image

    everglot-app-test:
        environment:
            NODE_ENV: "development"
            ROARR_LOG: "true"
            PGUSER: ${POSTGRES_USER:?Please set POSTGRES_USER}
            PGPASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
            PGDATABASE: ${POSTGRES_DB:?Please set POSTGRES_DB}
            PGHOST: ${PGHOST:-everglot-db}
            PGPORT: ${PGPORT:-5432}
            DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PGHOST:-everglot-db}:${PGPORT}/${POSTGRES_DB}"
            SESSION_COOKIE_VALIDATION_SECRETS: ${SESSION_COOKIE_VALIDATION_SECRETS:?Please set SESSION_COOKIE_VALIDATION_SECRETS}
            AGORA_APP_CERTIFICATE: ""
            SENDINBLUE_API_KEY: ""
            REFRESH_TOKEN_SECRET_KEY: |
                {
                    "crv": "Ed25519",
                    "d": "oQwKotJRpwz-Y71TGvYWlaXAQ1FCZ8SBUpBHxco3560",
                    "x": "OfWEsfD3Uh9GRB3JcSAcrw5VC9MRBT-da3OH7MaSZf8",
                    "kty": "OKP",
                    "kid": "484fa1cd-f0a0-4a8f-a8b5-170db41de1ac",
                }
            REFRESH_TOKEN_JWKS: |
                {
                    "keys":
                        [
                            {
                                "crv": "Ed25519",
                                "x": "OfWEsfD3Uh9GRB3JcSAcrw5VC9MRBT-da3OH7MaSZf8",
                                "kty": "OKP",
                                "kid": "484fa1cd-f0a0-4a8f-a8b5-170db41de1ac",
                            },
                        ],
                }
        entrypoint: entrypoints/test-after-app.sh
        # Avoid building the same image twice.
        image: everglot-app-image
        depends_on:
            - everglot-app
        volumes:
            - ./:/home/node/app

    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
        ports:
            - "127.0.0.1:5442:5432"
