version: "3"

services:
    everglot-app:
        volumes:
            - ./:/home/node/app
        ports:
            - "127.0.0.1:8002:3000"
            - "127.0.0.1:10000:10000"
        environment:
            NODE_ENV: "development"
            ROARR_LOG: "true"
            HOST: "0.0.0.0"
            PORT: "3000"
        entrypoint: entrypoints/dev.sh
        command: ["/bin/sh", "-c", "npm run dev | roarr pretty-print"]

    everglot-db:
        environment:
            POSTGRES_USER: "everglot_app_user"
            POSTGRES_PASSWORD: "everglot_app_pass"
            POSTGRES_DB: "everglot_app_db"
        ports:
            - "127.0.0.1:5432:5432"
