on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        if: github.ref != 'refs/heads/main'
        steps:
            - name: "Checkout"
              uses: actions/checkout@main
            - name: "Create .env file"
              run: |
                  echo "POSTGRES_USER=everglot_app_user" >> .env
                  echo "POSTGRES_PASSWORD=everglot_app_pass" >> .env
                  echo "POSTGRES_DB=everglot_app_db" >> .env
                  echo "SESSION_COOKIE_VALIDATION_SECRETS=[\"MySecretCookieValidationSecret123\"]" >> .env
            - name: Build app docker image
              run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml build --build-arg NODE_ENV=development --parallel everglot-app
            - name: Start database
              run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d everglot-db
            - name: Migrate database and start app
              run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run -d everglot-app
            - name: Run tests
              run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --entrypoint entrypoints/ci.sh everglot-app npm run test:pretty
    build:
        name: Build, Push and Deploy
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout main
              uses: actions/checkout@main
              with:
                  ref: main

            - name: Checkout k8s-setup repo
              uses: actions/checkout@main
              with:
                  repository: everglotapp/k8s-setup
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
                  path: k8s-setup
                  ref: main

            - name: Build container image
              run: docker build -t registry.digitalocean.com/everglot/everglot:latest .

            - name: Install doctl
              uses: digitalocean/action-doctl@v2.1.0
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 600

            - name: Push image to DigitalOcean Container Registry
              run: docker push registry.digitalocean.com/everglot/everglot:latest

            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-20-2-do-0-ams3-1612982708095

            - name: Delete Postgres Kubernetes Secrets if existed
              run: kubectl delete secret postgres --ignore-not-found

            - name: Inject Postgres Kubernetes Secrets from Github Secrets
              run: kubectl create secret generic postgres --from-literal=postgres-password='${{ secrets.PGPASSWORD }}'

            - name: Delete Session Secrets from Kubernetes Secrets if existed
              run: kubectl delete secret session --ignore-not-found

            - name: Inject Session Secrets from Github Secrets
              run: kubectl create secret generic session --from-literal=session-cookie-validation-secrets='${{ secrets.SESSION_COOKIE_VALIDATION_SECRETS }}'

            - name: Deploy Config to DigitalOcean Kubernetes
              run: kubectl apply -f $GITHUB_WORKSPACE/k8s-setup/everglot/service-deployment.yml

            - name: Rollout Deployment to DigitalOcean Kubernetes
              run: kubectl rollout restart deployment/everglot

            - name: Verify deployment
              run: kubectl rollout status deployment/everglot
